spring:
    # DB ??
    datasource:
        # ??? H2 DB? ?? URL
        url: jdbc:h2:tcp://localhost/~/hackerton
        # ??? ?? ????
        driver-class-name: org.h2.Driver
        # springboot 2.4 ??? username? ? ??????. ??? ??? ?????.
        username: sa
    jpa:
        hibernate:
            ddl-auto: update
        #hbm2ddl.auto: update
#            dialect: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                show_sql: true
                format_sql: true

    logging.level:
        org.hibernate.SQL: debug
    # 파일 크기 제한 30MB로 확장
    servlet:
        multipart:
            max-file-size: 30MB
            max-request-size: 30MB


cloud:
    aws:
        credentials:
            accessKey: ${AWS_ACCESS_KEY_ID}       # AWS IAM AccessKey 적기
            secretKey: ${AWS_SECRET_ACCESS_KEY}   # AWS IAM SecretKey 적기
        s3:
            bucket: ${AWS_S3_BUCKET_NAME}
        region:
            static: ap-northeast-2
        stack:
            auto: false