spring:
    # DB ??
    datasource:
        # ??? H2 DB? ?? URL
        url: jdbc:h2:tcp://localhost/~/hackerton
        # ??? ?? ????
        driver-class-name: org.h2.Driver
        # springboot 2.4 ??? username? ? ??????. ??? ??? ?????.
        username: sa
    jpa:
        hibernate:
            hbm2ddl.auto: update
        properties:
            hibernate:
                show_sql: true
                format_sql: true

    logging.level:
        org.hibernate.SQL: debug
